### ISSUE TITLE
Clicking through the menu bar to the buttons underneath

### ISSUE THREAD

**Issue by cheungpat** [furudean/type-kana#536]
I found it possible to click it through the menu bar to the buttons below it. This sometimes affect the kana selection when I click the start quiz button.

To reproduce:

1. Go to the quiz
2. Switch on “both” mode
3. Scroll / Resize window so that some kana buttons are underneath the menu bar
4. Click on the button through the menu bar

Demonstration:

https://github.com/furudean/type-kana/assets/170071/c3ae62b0-2578-4b2c-9100-12e66a7a8e30

**Comment by furudean** [comment]
Fixed in 537
